list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_rifle_ak47", title = "[NPCW] L4D2 AK-47"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_auto_shotgun", title = "[NPCW] L4D2 AUTO SHOTGUN"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_shotgun_chrome", title = "[NPCW] L4D2 CHROME SHOTGUN"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_rifle_desert", title = "[NPCW] L4D2 DESERT RIFLE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_hunting_rifle", title = "[NPCW] L4D2 HUNTING RIFLE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_machinegun_m60", title = "[NPCW] L4D2 M60"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_magnum", title = "[NPCW] L4D2 MAGNUM"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_sniper_military", title = "[NPCW] L4D2 MILITARY SNIPER"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_pistol", title = "[NPCW] L4D2 PISTOL"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_shotgun", title = "[NPCW] L4D2 PUMP SHOTGUN"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_rifle", title = "[NPCW] L4D2 RIFLE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_second_pistol", title = "[NPCW] L4D2 SECOND PISTOL"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_smg_silenced", title = "[NPCW] L4D2 SILENCED SMG"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_smg", title = "[NPCW] L4D2 SMG"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_auto_shotgun_spas", title = "[NPCW] L4D2 SPAS-12"})

list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_random_pistol", title = "[NPCW] [RANDOM] L4D2 PISTOL"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_random_rifle", title = "[NPCW] [RANDOM] L4D2 RIFLE"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_random_shotgun", title = "[NPCW] [RANDOM] L4D2 SHOTGUN"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_random_smg", title = "[NPCW] [RANDOM] L4D2 SMG"})
list.Add("NPCUsableWeapons", {class = "swep_ai_l4d2_random_sniper", title = "[NPCW] [RANDOM] L4D2 SNIPER"})